const firstName = "Aseel";
const lastName="Elm";
const age=10;
const dateOfBirth= "05/01/2010";
const address= "Saratoga Place";
 console.log("Firstname: ", firstName  );
 console.log("Lastname: ", lastName);
 console.log("Age: ", age,);
 console.log("Date of Birth: ",dateOfBirth);
 console.log("Address", address);