var age =30;
var phone =613000000;
 var streetName= "Saratoga";
var streetNumber= 2701;
var firstMessage=`I'am ${age} years old`;
console.log(firstMessage);
var secondMessage=`My phone number is: ${phone}`;
console.log(secondMessage);
var thirdMessage= `I live on ${streetNumber} ${streetName}`;
console.log(thirdMessage);