var firstName = "Aseel";
var lastName="Elm";
 var age=10;
var  dateOfBirth= "05/01/2010";
 var address= "Saratoga Place";
 console.log("Firstname: ", firstName  );
 console.log("Lastname: ", lastName);
 console.log("Age: ", age,);
 console.log("DoB: ",dateOfBirth);
 console.log("Address", address);